Hello microverse
solog0039/Hello1-Microverse pull request #1
Opened 2023-01-10 20:13 UTC by solog0039

In this project:
>Github work flow created
>HTML file created
>CSS file created
>Linter installed

2023-01-10 20:46 UTC, Ibizugbe requested changes
Hi @solog0039 👋, 

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f69656d6d596a3332456945655a59766a70712f67697068792e676966](https://user-images.githubusercontent.com/64643995/211658553-1787f3c3-65c9-4c82-b691-0db853bff350.gif)

Good job so far!🤗🤗
There are some issues that you still need to work on to go to the next project but you are almost there!👍

## Highlights

- [ ] All linter checks are passing.
- [ ] The right github flow method has been used.

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- [OPTIONAL]  I think you can make your commit messages more descriptive in your future project as this makes your project appear more professioal. I will suggest you take a look at [this article](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/articles/professional_repo_rules.md) so as to help you improve.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-10 20:46 UTC, Ibizugbe commented on README.md
> +This project is MIT License licensed.
I can see you made a great effort creating your readme👍, to make our projects look more professional, It is a requirement that we make use of the [Microverse readme template](https://github.com/microverseinc/readme-template/blob/master/README.md)😉 kindly make use the given [Microverse template](https://github.com/microverseinc/readme-template/blob/master/README.md) to create your readme.

2023-01-14 20:29 UTC, wayungi requested changes
Hi @solog0039 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights ⭐ ⭐ 
- [ ] Correct GitHub flow
- [ ]  All linter checks passing


## Required Changes ♻️
 - [ ] Please use this [README](https://github.com/microverseinc/readme-template)  for all your README files and do not remove any sections except for the FAQs 📖 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

 - [OPTIONAL ] You can also write better commit messages using the imperative tense. It is better to commit after every feature. For example, when you add a navigation bar, you can commit with a message like **Add nav bar**. Please remember to do this in your next commit messages 👏🏾 
 
- [OPTIONAL] Please create a file called **test.md** and add the following content to that file "_This file should be ignored by git_" 👏🏾 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 20:29 UTC, wayungi commented on README.md
> +This project is Apache License licensed.
- [ ] Please as requested by the previous reviewer, use [this README template](https://github.com/microverseinc/readme-template). Using a professional README template makes your repo professional.

2023-01-14 21:19 UTC, MeqdamAlqudah approved these changes
Hi @solog0039 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![image](https://user-images.githubusercontent.com/74744787/212497431-4a196852-0da7-4dd1-85c2-2f98de561b48.png)

## Highlights 
:+1: no linter errors

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-14 21:33 UTC, merged